// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settingsu3d2dms.proto

public final class Settingsu3D2Dms {
  private Settingsu3D2Dms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CALIB = 0;</code>
     */
    CALIB(0),
    /**
     * <code>REGIST = 1;</code>
     */
    REGIST(1),
    /**
     * <pre>
     * mouth
     * </pre>
     *
     * <code>MOUTH_THRESH = 2;</code>
     */
    MOUTH_THRESH(2),
    /**
     * <code>YAWN_ALARM_TIME = 3;</code>
     */
    YAWN_ALARM_TIME(3),
    /**
     * <pre>
     * eyes
     * </pre>
     *
     * <code>LEFT_EYE_THRESH = 4;</code>
     */
    LEFT_EYE_THRESH(4),
    /**
     * <code>RIGHT_EYE_THRESH = 5;</code>
     */
    RIGHT_EYE_THRESH(5),
    /**
     * <code>DOZE_ALARM_TIME = 6;</code>
     */
    DOZE_ALARM_TIME(6),
    /**
     * <code>PHONE_ALARM_TIME = 7;</code>
     */
    PHONE_ALARM_TIME(7),
    /**
     * <code>SMOKING_ALARM_TIME = 8;</code>
     */
    SMOKING_ALARM_TIME(8),
    ;

    /**
     * <code>CALIB = 0;</code>
     */
    public static final int CALIB_VALUE = 0;
    /**
     * <code>REGIST = 1;</code>
     */
    public static final int REGIST_VALUE = 1;
    /**
     * <pre>
     * mouth
     * </pre>
     *
     * <code>MOUTH_THRESH = 2;</code>
     */
    public static final int MOUTH_THRESH_VALUE = 2;
    /**
     * <code>YAWN_ALARM_TIME = 3;</code>
     */
    public static final int YAWN_ALARM_TIME_VALUE = 3;
    /**
     * <pre>
     * eyes
     * </pre>
     *
     * <code>LEFT_EYE_THRESH = 4;</code>
     */
    public static final int LEFT_EYE_THRESH_VALUE = 4;
    /**
     * <code>RIGHT_EYE_THRESH = 5;</code>
     */
    public static final int RIGHT_EYE_THRESH_VALUE = 5;
    /**
     * <code>DOZE_ALARM_TIME = 6;</code>
     */
    public static final int DOZE_ALARM_TIME_VALUE = 6;
    /**
     * <code>PHONE_ALARM_TIME = 7;</code>
     */
    public static final int PHONE_ALARM_TIME_VALUE = 7;
    /**
     * <code>SMOKING_ALARM_TIME = 8;</code>
     */
    public static final int SMOKING_ALARM_TIME_VALUE = 8;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return CALIB;
        case 1: return REGIST;
        case 2: return MOUTH_THRESH;
        case 3: return YAWN_ALARM_TIME;
        case 4: return LEFT_EYE_THRESH;
        case 5: return RIGHT_EYE_THRESH;
        case 6: return DOZE_ALARM_TIME;
        case 7: return PHONE_ALARM_TIME;
        case 8: return SMOKING_ALARM_TIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Settingsu3D2Dms.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ActionType)
  }

  public interface SettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Settings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    java.util.List<Settingsu3D2Dms.ActionType> getActionsList();
    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    int getActionsCount();
    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    Settingsu3D2Dms.ActionType getActions(int index);

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * mouth settings
     * </pre>
     *
     * <code>optional float mouth_thresh = 3;</code>
     */
    boolean hasMouthThresh();
    /**
     * <pre>
     * mouth settings
     * </pre>
     *
     * <code>optional float mouth_thresh = 3;</code>
     */
    float getMouthThresh();

    /**
     * <code>optional float yawn_alarm_time = 4;</code>
     */
    boolean hasYawnAlarmTime();
    /**
     * <code>optional float yawn_alarm_time = 4;</code>
     */
    float getYawnAlarmTime();

    /**
     * <pre>
     * eye settings
     * </pre>
     *
     * <code>optional float left_eye_thresh = 5;</code>
     */
    boolean hasLeftEyeThresh();
    /**
     * <pre>
     * eye settings
     * </pre>
     *
     * <code>optional float left_eye_thresh = 5;</code>
     */
    float getLeftEyeThresh();

    /**
     * <code>optional float right_eye_thresh = 6;</code>
     */
    boolean hasRightEyeThresh();
    /**
     * <code>optional float right_eye_thresh = 6;</code>
     */
    float getRightEyeThresh();

    /**
     * <code>optional float doze_alarm_time = 7;</code>
     */
    boolean hasDozeAlarmTime();
    /**
     * <code>optional float doze_alarm_time = 7;</code>
     */
    float getDozeAlarmTime();

    /**
     * <pre>
     * phone settings
     * </pre>
     *
     * <code>optional float phone_alarm_time = 8;</code>
     */
    boolean hasPhoneAlarmTime();
    /**
     * <pre>
     * phone settings
     * </pre>
     *
     * <code>optional float phone_alarm_time = 8;</code>
     */
    float getPhoneAlarmTime();

    /**
     * <code>optional float smoking_alarm_time = 9;</code>
     */
    boolean hasSmokingAlarmTime();
    /**
     * <code>optional float smoking_alarm_time = 9;</code>
     */
    float getSmokingAlarmTime();

    /**
     * <code>optional float left_distraction_limit = 10;</code>
     */
    boolean hasLeftDistractionLimit();
    /**
     * <code>optional float left_distraction_limit = 10;</code>
     */
    float getLeftDistractionLimit();

    /**
     * <code>optional float right_distraction_limit = 11;</code>
     */
    boolean hasRightDistractionLimit();
    /**
     * <code>optional float right_distraction_limit = 11;</code>
     */
    float getRightDistractionLimit();

    /**
     * <code>optional float down_distraction_limit = 12;</code>
     */
    boolean hasDownDistractionLimit();
    /**
     * <code>optional float down_distraction_limit = 12;</code>
     */
    float getDownDistractionLimit();

    /**
     * <code>optional float up_distraction_limit = 13;</code>
     */
    boolean hasUpDistractionLimit();
    /**
     * <code>optional float up_distraction_limit = 13;</code>
     */
    float getUpDistractionLimit();
  }
  /**
   * Protobuf type {@code Settings}
   */
  public  static final class Settings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Settings)
      SettingsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Settings.newBuilder() to construct.
    private Settings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Settings() {
      actions_ = java.util.Collections.emptyList();
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Settings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
              Settingsu3D2Dms.ActionType value = Settingsu3D2Dms.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  actions_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                actions_.add(rawValue);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
                Settingsu3D2Dms.ActionType value = Settingsu3D2Dms.ActionType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                    actions_ = new java.util.ArrayList<java.lang.Integer>();
                    mutable_bitField0_ |= 0x00000001;
                  }
                  actions_.add(rawValue);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000002;
              mouthThresh_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000004;
              yawnAlarmTime_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000008;
              leftEyeThresh_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000010;
              rightEyeThresh_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000020;
              dozeAlarmTime_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000040;
              phoneAlarmTime_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000080;
              smokingAlarmTime_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000100;
              leftDistractionLimit_ = input.readFloat();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000200;
              rightDistractionLimit_ = input.readFloat();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000400;
              downDistractionLimit_ = input.readFloat();
              break;
            }
            case 109: {
              bitField0_ |= 0x00000800;
              upDistractionLimit_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Settingsu3D2Dms.internal_static_Settings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Settingsu3D2Dms.internal_static_Settings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Settingsu3D2Dms.Settings.class, Settingsu3D2Dms.Settings.Builder.class);
    }

    private int bitField0_;
    public static final int ACTIONS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> actions_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, Settingsu3D2Dms.ActionType> actions_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, Settingsu3D2Dms.ActionType>() {
              public Settingsu3D2Dms.ActionType convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                Settingsu3D2Dms.ActionType result = Settingsu3D2Dms.ActionType.valueOf(from);
                return result == null ? Settingsu3D2Dms.ActionType.CALIB : result;
              }
            };
    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    public java.util.List<Settingsu3D2Dms.ActionType> getActionsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, Settingsu3D2Dms.ActionType>(actions_, actions_converter_);
    }
    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    public int getActionsCount() {
      return actions_.size();
    }
    /**
     * <code>repeated .ActionType actions = 1;</code>
     */
    public Settingsu3D2Dms.ActionType getActions(int index) {
      return actions_converter_.convert(actions_.get(index));
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOUTH_THRESH_FIELD_NUMBER = 3;
    private float mouthThresh_;
    /**
     * <pre>
     * mouth settings
     * </pre>
     *
     * <code>optional float mouth_thresh = 3;</code>
     */
    public boolean hasMouthThresh() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * mouth settings
     * </pre>
     *
     * <code>optional float mouth_thresh = 3;</code>
     */
    public float getMouthThresh() {
      return mouthThresh_;
    }

    public static final int YAWN_ALARM_TIME_FIELD_NUMBER = 4;
    private float yawnAlarmTime_;
    /**
     * <code>optional float yawn_alarm_time = 4;</code>
     */
    public boolean hasYawnAlarmTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional float yawn_alarm_time = 4;</code>
     */
    public float getYawnAlarmTime() {
      return yawnAlarmTime_;
    }

    public static final int LEFT_EYE_THRESH_FIELD_NUMBER = 5;
    private float leftEyeThresh_;
    /**
     * <pre>
     * eye settings
     * </pre>
     *
     * <code>optional float left_eye_thresh = 5;</code>
     */
    public boolean hasLeftEyeThresh() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * eye settings
     * </pre>
     *
     * <code>optional float left_eye_thresh = 5;</code>
     */
    public float getLeftEyeThresh() {
      return leftEyeThresh_;
    }

    public static final int RIGHT_EYE_THRESH_FIELD_NUMBER = 6;
    private float rightEyeThresh_;
    /**
     * <code>optional float right_eye_thresh = 6;</code>
     */
    public boolean hasRightEyeThresh() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float right_eye_thresh = 6;</code>
     */
    public float getRightEyeThresh() {
      return rightEyeThresh_;
    }

    public static final int DOZE_ALARM_TIME_FIELD_NUMBER = 7;
    private float dozeAlarmTime_;
    /**
     * <code>optional float doze_alarm_time = 7;</code>
     */
    public boolean hasDozeAlarmTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional float doze_alarm_time = 7;</code>
     */
    public float getDozeAlarmTime() {
      return dozeAlarmTime_;
    }

    public static final int PHONE_ALARM_TIME_FIELD_NUMBER = 8;
    private float phoneAlarmTime_;
    /**
     * <pre>
     * phone settings
     * </pre>
     *
     * <code>optional float phone_alarm_time = 8;</code>
     */
    public boolean hasPhoneAlarmTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * phone settings
     * </pre>
     *
     * <code>optional float phone_alarm_time = 8;</code>
     */
    public float getPhoneAlarmTime() {
      return phoneAlarmTime_;
    }

    public static final int SMOKING_ALARM_TIME_FIELD_NUMBER = 9;
    private float smokingAlarmTime_;
    /**
     * <code>optional float smoking_alarm_time = 9;</code>
     */
    public boolean hasSmokingAlarmTime() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional float smoking_alarm_time = 9;</code>
     */
    public float getSmokingAlarmTime() {
      return smokingAlarmTime_;
    }

    public static final int LEFT_DISTRACTION_LIMIT_FIELD_NUMBER = 10;
    private float leftDistractionLimit_;
    /**
     * <code>optional float left_distraction_limit = 10;</code>
     */
    public boolean hasLeftDistractionLimit() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional float left_distraction_limit = 10;</code>
     */
    public float getLeftDistractionLimit() {
      return leftDistractionLimit_;
    }

    public static final int RIGHT_DISTRACTION_LIMIT_FIELD_NUMBER = 11;
    private float rightDistractionLimit_;
    /**
     * <code>optional float right_distraction_limit = 11;</code>
     */
    public boolean hasRightDistractionLimit() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional float right_distraction_limit = 11;</code>
     */
    public float getRightDistractionLimit() {
      return rightDistractionLimit_;
    }

    public static final int DOWN_DISTRACTION_LIMIT_FIELD_NUMBER = 12;
    private float downDistractionLimit_;
    /**
     * <code>optional float down_distraction_limit = 12;</code>
     */
    public boolean hasDownDistractionLimit() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional float down_distraction_limit = 12;</code>
     */
    public float getDownDistractionLimit() {
      return downDistractionLimit_;
    }

    public static final int UP_DISTRACTION_LIMIT_FIELD_NUMBER = 13;
    private float upDistractionLimit_;
    /**
     * <code>optional float up_distraction_limit = 13;</code>
     */
    public boolean hasUpDistractionLimit() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional float up_distraction_limit = 13;</code>
     */
    public float getUpDistractionLimit() {
      return upDistractionLimit_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < actions_.size(); i++) {
        output.writeEnum(1, actions_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(3, mouthThresh_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(4, yawnAlarmTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(5, leftEyeThresh_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(6, rightEyeThresh_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFloat(7, dozeAlarmTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeFloat(8, phoneAlarmTime_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeFloat(9, smokingAlarmTime_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeFloat(10, leftDistractionLimit_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeFloat(11, rightDistractionLimit_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeFloat(12, downDistractionLimit_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeFloat(13, upDistractionLimit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < actions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(actions_.get(i));
        }
        size += dataSize;
        size += 1 * actions_.size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, mouthThresh_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, yawnAlarmTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, leftEyeThresh_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, rightEyeThresh_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, dozeAlarmTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, phoneAlarmTime_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, smokingAlarmTime_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, leftDistractionLimit_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, rightDistractionLimit_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, downDistractionLimit_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, upDistractionLimit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Settingsu3D2Dms.Settings)) {
        return super.equals(obj);
      }
      Settingsu3D2Dms.Settings other = (Settingsu3D2Dms.Settings) obj;

      if (!actions_.equals(other.actions_)) return false;
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasMouthThresh() != other.hasMouthThresh()) return false;
      if (hasMouthThresh()) {
        if (java.lang.Float.floatToIntBits(getMouthThresh())
            != java.lang.Float.floatToIntBits(
                other.getMouthThresh())) return false;
      }
      if (hasYawnAlarmTime() != other.hasYawnAlarmTime()) return false;
      if (hasYawnAlarmTime()) {
        if (java.lang.Float.floatToIntBits(getYawnAlarmTime())
            != java.lang.Float.floatToIntBits(
                other.getYawnAlarmTime())) return false;
      }
      if (hasLeftEyeThresh() != other.hasLeftEyeThresh()) return false;
      if (hasLeftEyeThresh()) {
        if (java.lang.Float.floatToIntBits(getLeftEyeThresh())
            != java.lang.Float.floatToIntBits(
                other.getLeftEyeThresh())) return false;
      }
      if (hasRightEyeThresh() != other.hasRightEyeThresh()) return false;
      if (hasRightEyeThresh()) {
        if (java.lang.Float.floatToIntBits(getRightEyeThresh())
            != java.lang.Float.floatToIntBits(
                other.getRightEyeThresh())) return false;
      }
      if (hasDozeAlarmTime() != other.hasDozeAlarmTime()) return false;
      if (hasDozeAlarmTime()) {
        if (java.lang.Float.floatToIntBits(getDozeAlarmTime())
            != java.lang.Float.floatToIntBits(
                other.getDozeAlarmTime())) return false;
      }
      if (hasPhoneAlarmTime() != other.hasPhoneAlarmTime()) return false;
      if (hasPhoneAlarmTime()) {
        if (java.lang.Float.floatToIntBits(getPhoneAlarmTime())
            != java.lang.Float.floatToIntBits(
                other.getPhoneAlarmTime())) return false;
      }
      if (hasSmokingAlarmTime() != other.hasSmokingAlarmTime()) return false;
      if (hasSmokingAlarmTime()) {
        if (java.lang.Float.floatToIntBits(getSmokingAlarmTime())
            != java.lang.Float.floatToIntBits(
                other.getSmokingAlarmTime())) return false;
      }
      if (hasLeftDistractionLimit() != other.hasLeftDistractionLimit()) return false;
      if (hasLeftDistractionLimit()) {
        if (java.lang.Float.floatToIntBits(getLeftDistractionLimit())
            != java.lang.Float.floatToIntBits(
                other.getLeftDistractionLimit())) return false;
      }
      if (hasRightDistractionLimit() != other.hasRightDistractionLimit()) return false;
      if (hasRightDistractionLimit()) {
        if (java.lang.Float.floatToIntBits(getRightDistractionLimit())
            != java.lang.Float.floatToIntBits(
                other.getRightDistractionLimit())) return false;
      }
      if (hasDownDistractionLimit() != other.hasDownDistractionLimit()) return false;
      if (hasDownDistractionLimit()) {
        if (java.lang.Float.floatToIntBits(getDownDistractionLimit())
            != java.lang.Float.floatToIntBits(
                other.getDownDistractionLimit())) return false;
      }
      if (hasUpDistractionLimit() != other.hasUpDistractionLimit()) return false;
      if (hasUpDistractionLimit()) {
        if (java.lang.Float.floatToIntBits(getUpDistractionLimit())
            != java.lang.Float.floatToIntBits(
                other.getUpDistractionLimit())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActionsCount() > 0) {
        hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + actions_.hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasMouthThresh()) {
        hash = (37 * hash) + MOUTH_THRESH_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getMouthThresh());
      }
      if (hasYawnAlarmTime()) {
        hash = (37 * hash) + YAWN_ALARM_TIME_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getYawnAlarmTime());
      }
      if (hasLeftEyeThresh()) {
        hash = (37 * hash) + LEFT_EYE_THRESH_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLeftEyeThresh());
      }
      if (hasRightEyeThresh()) {
        hash = (37 * hash) + RIGHT_EYE_THRESH_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRightEyeThresh());
      }
      if (hasDozeAlarmTime()) {
        hash = (37 * hash) + DOZE_ALARM_TIME_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getDozeAlarmTime());
      }
      if (hasPhoneAlarmTime()) {
        hash = (37 * hash) + PHONE_ALARM_TIME_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPhoneAlarmTime());
      }
      if (hasSmokingAlarmTime()) {
        hash = (37 * hash) + SMOKING_ALARM_TIME_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSmokingAlarmTime());
      }
      if (hasLeftDistractionLimit()) {
        hash = (37 * hash) + LEFT_DISTRACTION_LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLeftDistractionLimit());
      }
      if (hasRightDistractionLimit()) {
        hash = (37 * hash) + RIGHT_DISTRACTION_LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRightDistractionLimit());
      }
      if (hasDownDistractionLimit()) {
        hash = (37 * hash) + DOWN_DISTRACTION_LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getDownDistractionLimit());
      }
      if (hasUpDistractionLimit()) {
        hash = (37 * hash) + UP_DISTRACTION_LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getUpDistractionLimit());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Settingsu3D2Dms.Settings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Settingsu3D2Dms.Settings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Settingsu3D2Dms.Settings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Settingsu3D2Dms.Settings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Settingsu3D2Dms.Settings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Settingsu3D2Dms.Settings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Settingsu3D2Dms.Settings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Settings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Settings)
        Settingsu3D2Dms.SettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Settingsu3D2Dms.internal_static_Settings_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Settingsu3D2Dms.internal_static_Settings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Settingsu3D2Dms.Settings.class, Settingsu3D2Dms.Settings.Builder.class);
      }

      // Construct using Settingsu3D2Dms.Settings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        actions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mouthThresh_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        yawnAlarmTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        leftEyeThresh_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        rightEyeThresh_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        dozeAlarmTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        phoneAlarmTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        smokingAlarmTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        leftDistractionLimit_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        rightDistractionLimit_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000400);
        downDistractionLimit_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        upDistractionLimit_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Settingsu3D2Dms.internal_static_Settings_descriptor;
      }

      @java.lang.Override
      public Settingsu3D2Dms.Settings getDefaultInstanceForType() {
        return Settingsu3D2Dms.Settings.getDefaultInstance();
      }

      @java.lang.Override
      public Settingsu3D2Dms.Settings build() {
        Settingsu3D2Dms.Settings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Settingsu3D2Dms.Settings buildPartial() {
        Settingsu3D2Dms.Settings result = new Settingsu3D2Dms.Settings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.actions_ = actions_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mouthThresh_ = mouthThresh_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.yawnAlarmTime_ = yawnAlarmTime_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.leftEyeThresh_ = leftEyeThresh_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.rightEyeThresh_ = rightEyeThresh_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.dozeAlarmTime_ = dozeAlarmTime_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.phoneAlarmTime_ = phoneAlarmTime_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.smokingAlarmTime_ = smokingAlarmTime_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.leftDistractionLimit_ = leftDistractionLimit_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.rightDistractionLimit_ = rightDistractionLimit_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.downDistractionLimit_ = downDistractionLimit_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.upDistractionLimit_ = upDistractionLimit_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Settingsu3D2Dms.Settings) {
          return mergeFrom((Settingsu3D2Dms.Settings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Settingsu3D2Dms.Settings other) {
        if (other == Settingsu3D2Dms.Settings.getDefaultInstance()) return this;
        if (!other.actions_.isEmpty()) {
          if (actions_.isEmpty()) {
            actions_ = other.actions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActionsIsMutable();
            actions_.addAll(other.actions_);
          }
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMouthThresh()) {
          setMouthThresh(other.getMouthThresh());
        }
        if (other.hasYawnAlarmTime()) {
          setYawnAlarmTime(other.getYawnAlarmTime());
        }
        if (other.hasLeftEyeThresh()) {
          setLeftEyeThresh(other.getLeftEyeThresh());
        }
        if (other.hasRightEyeThresh()) {
          setRightEyeThresh(other.getRightEyeThresh());
        }
        if (other.hasDozeAlarmTime()) {
          setDozeAlarmTime(other.getDozeAlarmTime());
        }
        if (other.hasPhoneAlarmTime()) {
          setPhoneAlarmTime(other.getPhoneAlarmTime());
        }
        if (other.hasSmokingAlarmTime()) {
          setSmokingAlarmTime(other.getSmokingAlarmTime());
        }
        if (other.hasLeftDistractionLimit()) {
          setLeftDistractionLimit(other.getLeftDistractionLimit());
        }
        if (other.hasRightDistractionLimit()) {
          setRightDistractionLimit(other.getRightDistractionLimit());
        }
        if (other.hasDownDistractionLimit()) {
          setDownDistractionLimit(other.getDownDistractionLimit());
        }
        if (other.hasUpDistractionLimit()) {
          setUpDistractionLimit(other.getUpDistractionLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Settingsu3D2Dms.Settings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Settingsu3D2Dms.Settings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> actions_ =
        java.util.Collections.emptyList();
      private void ensureActionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          actions_ = new java.util.ArrayList<java.lang.Integer>(actions_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public java.util.List<Settingsu3D2Dms.ActionType> getActionsList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, Settingsu3D2Dms.ActionType>(actions_, actions_converter_);
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public int getActionsCount() {
        return actions_.size();
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public Settingsu3D2Dms.ActionType getActions(int index) {
        return actions_converter_.convert(actions_.get(index));
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public Builder setActions(
          int index, Settingsu3D2Dms.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public Builder addActions(Settingsu3D2Dms.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public Builder addAllActions(
          java.lang.Iterable<? extends Settingsu3D2Dms.ActionType> values) {
        ensureActionsIsMutable();
        for (Settingsu3D2Dms.ActionType value : values) {
          actions_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ActionType actions = 1;</code>
       */
      public Builder clearActions() {
        actions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private float mouthThresh_ ;
      /**
       * <pre>
       * mouth settings
       * </pre>
       *
       * <code>optional float mouth_thresh = 3;</code>
       */
      public boolean hasMouthThresh() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * mouth settings
       * </pre>
       *
       * <code>optional float mouth_thresh = 3;</code>
       */
      public float getMouthThresh() {
        return mouthThresh_;
      }
      /**
       * <pre>
       * mouth settings
       * </pre>
       *
       * <code>optional float mouth_thresh = 3;</code>
       */
      public Builder setMouthThresh(float value) {
        bitField0_ |= 0x00000004;
        mouthThresh_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * mouth settings
       * </pre>
       *
       * <code>optional float mouth_thresh = 3;</code>
       */
      public Builder clearMouthThresh() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mouthThresh_ = 0F;
        onChanged();
        return this;
      }

      private float yawnAlarmTime_ ;
      /**
       * <code>optional float yawn_alarm_time = 4;</code>
       */
      public boolean hasYawnAlarmTime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional float yawn_alarm_time = 4;</code>
       */
      public float getYawnAlarmTime() {
        return yawnAlarmTime_;
      }
      /**
       * <code>optional float yawn_alarm_time = 4;</code>
       */
      public Builder setYawnAlarmTime(float value) {
        bitField0_ |= 0x00000008;
        yawnAlarmTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float yawn_alarm_time = 4;</code>
       */
      public Builder clearYawnAlarmTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        yawnAlarmTime_ = 0F;
        onChanged();
        return this;
      }

      private float leftEyeThresh_ ;
      /**
       * <pre>
       * eye settings
       * </pre>
       *
       * <code>optional float left_eye_thresh = 5;</code>
       */
      public boolean hasLeftEyeThresh() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * eye settings
       * </pre>
       *
       * <code>optional float left_eye_thresh = 5;</code>
       */
      public float getLeftEyeThresh() {
        return leftEyeThresh_;
      }
      /**
       * <pre>
       * eye settings
       * </pre>
       *
       * <code>optional float left_eye_thresh = 5;</code>
       */
      public Builder setLeftEyeThresh(float value) {
        bitField0_ |= 0x00000010;
        leftEyeThresh_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * eye settings
       * </pre>
       *
       * <code>optional float left_eye_thresh = 5;</code>
       */
      public Builder clearLeftEyeThresh() {
        bitField0_ = (bitField0_ & ~0x00000010);
        leftEyeThresh_ = 0F;
        onChanged();
        return this;
      }

      private float rightEyeThresh_ ;
      /**
       * <code>optional float right_eye_thresh = 6;</code>
       */
      public boolean hasRightEyeThresh() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional float right_eye_thresh = 6;</code>
       */
      public float getRightEyeThresh() {
        return rightEyeThresh_;
      }
      /**
       * <code>optional float right_eye_thresh = 6;</code>
       */
      public Builder setRightEyeThresh(float value) {
        bitField0_ |= 0x00000020;
        rightEyeThresh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float right_eye_thresh = 6;</code>
       */
      public Builder clearRightEyeThresh() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rightEyeThresh_ = 0F;
        onChanged();
        return this;
      }

      private float dozeAlarmTime_ ;
      /**
       * <code>optional float doze_alarm_time = 7;</code>
       */
      public boolean hasDozeAlarmTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional float doze_alarm_time = 7;</code>
       */
      public float getDozeAlarmTime() {
        return dozeAlarmTime_;
      }
      /**
       * <code>optional float doze_alarm_time = 7;</code>
       */
      public Builder setDozeAlarmTime(float value) {
        bitField0_ |= 0x00000040;
        dozeAlarmTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float doze_alarm_time = 7;</code>
       */
      public Builder clearDozeAlarmTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dozeAlarmTime_ = 0F;
        onChanged();
        return this;
      }

      private float phoneAlarmTime_ ;
      /**
       * <pre>
       * phone settings
       * </pre>
       *
       * <code>optional float phone_alarm_time = 8;</code>
       */
      public boolean hasPhoneAlarmTime() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * phone settings
       * </pre>
       *
       * <code>optional float phone_alarm_time = 8;</code>
       */
      public float getPhoneAlarmTime() {
        return phoneAlarmTime_;
      }
      /**
       * <pre>
       * phone settings
       * </pre>
       *
       * <code>optional float phone_alarm_time = 8;</code>
       */
      public Builder setPhoneAlarmTime(float value) {
        bitField0_ |= 0x00000080;
        phoneAlarmTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * phone settings
       * </pre>
       *
       * <code>optional float phone_alarm_time = 8;</code>
       */
      public Builder clearPhoneAlarmTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phoneAlarmTime_ = 0F;
        onChanged();
        return this;
      }

      private float smokingAlarmTime_ ;
      /**
       * <code>optional float smoking_alarm_time = 9;</code>
       */
      public boolean hasSmokingAlarmTime() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional float smoking_alarm_time = 9;</code>
       */
      public float getSmokingAlarmTime() {
        return smokingAlarmTime_;
      }
      /**
       * <code>optional float smoking_alarm_time = 9;</code>
       */
      public Builder setSmokingAlarmTime(float value) {
        bitField0_ |= 0x00000100;
        smokingAlarmTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float smoking_alarm_time = 9;</code>
       */
      public Builder clearSmokingAlarmTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        smokingAlarmTime_ = 0F;
        onChanged();
        return this;
      }

      private float leftDistractionLimit_ ;
      /**
       * <code>optional float left_distraction_limit = 10;</code>
       */
      public boolean hasLeftDistractionLimit() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional float left_distraction_limit = 10;</code>
       */
      public float getLeftDistractionLimit() {
        return leftDistractionLimit_;
      }
      /**
       * <code>optional float left_distraction_limit = 10;</code>
       */
      public Builder setLeftDistractionLimit(float value) {
        bitField0_ |= 0x00000200;
        leftDistractionLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float left_distraction_limit = 10;</code>
       */
      public Builder clearLeftDistractionLimit() {
        bitField0_ = (bitField0_ & ~0x00000200);
        leftDistractionLimit_ = 0F;
        onChanged();
        return this;
      }

      private float rightDistractionLimit_ ;
      /**
       * <code>optional float right_distraction_limit = 11;</code>
       */
      public boolean hasRightDistractionLimit() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional float right_distraction_limit = 11;</code>
       */
      public float getRightDistractionLimit() {
        return rightDistractionLimit_;
      }
      /**
       * <code>optional float right_distraction_limit = 11;</code>
       */
      public Builder setRightDistractionLimit(float value) {
        bitField0_ |= 0x00000400;
        rightDistractionLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float right_distraction_limit = 11;</code>
       */
      public Builder clearRightDistractionLimit() {
        bitField0_ = (bitField0_ & ~0x00000400);
        rightDistractionLimit_ = 0F;
        onChanged();
        return this;
      }

      private float downDistractionLimit_ ;
      /**
       * <code>optional float down_distraction_limit = 12;</code>
       */
      public boolean hasDownDistractionLimit() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional float down_distraction_limit = 12;</code>
       */
      public float getDownDistractionLimit() {
        return downDistractionLimit_;
      }
      /**
       * <code>optional float down_distraction_limit = 12;</code>
       */
      public Builder setDownDistractionLimit(float value) {
        bitField0_ |= 0x00000800;
        downDistractionLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float down_distraction_limit = 12;</code>
       */
      public Builder clearDownDistractionLimit() {
        bitField0_ = (bitField0_ & ~0x00000800);
        downDistractionLimit_ = 0F;
        onChanged();
        return this;
      }

      private float upDistractionLimit_ ;
      /**
       * <code>optional float up_distraction_limit = 13;</code>
       */
      public boolean hasUpDistractionLimit() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional float up_distraction_limit = 13;</code>
       */
      public float getUpDistractionLimit() {
        return upDistractionLimit_;
      }
      /**
       * <code>optional float up_distraction_limit = 13;</code>
       */
      public Builder setUpDistractionLimit(float value) {
        bitField0_ |= 0x00001000;
        upDistractionLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float up_distraction_limit = 13;</code>
       */
      public Builder clearUpDistractionLimit() {
        bitField0_ = (bitField0_ & ~0x00001000);
        upDistractionLimit_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Settings)
    }

    // @@protoc_insertion_point(class_scope:Settings)
    private static final Settingsu3D2Dms.Settings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Settingsu3D2Dms.Settings();
    }

    public static Settingsu3D2Dms.Settings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Settings>
        PARSER = new com.google.protobuf.AbstractParser<Settings>() {
      @java.lang.Override
      public Settings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Settings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Settings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Settings> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Settingsu3D2Dms.Settings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Settings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Settings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025settingsu3d2dms.proto\"\346\002\n\010Settings\022\034\n\007" +
      "actions\030\001 \003(\0162\013.ActionType\022\014\n\004name\030\002 \001(\t" +
      "\022\024\n\014mouth_thresh\030\003 \001(\002\022\027\n\017yawn_alarm_tim" +
      "e\030\004 \001(\002\022\027\n\017left_eye_thresh\030\005 \001(\002\022\030\n\020righ" +
      "t_eye_thresh\030\006 \001(\002\022\027\n\017doze_alarm_time\030\007 " +
      "\001(\002\022\030\n\020phone_alarm_time\030\010 \001(\002\022\032\n\022smoking" +
      "_alarm_time\030\t \001(\002\022\036\n\026left_distraction_li" +
      "mit\030\n \001(\002\022\037\n\027right_distraction_limit\030\013 \001" +
      "(\002\022\036\n\026down_distraction_limit\030\014 \001(\002\022\034\n\024up" +
      "_distraction_limit\030\r \001(\002*\270\001\n\nActionType\022" +
      "\t\n\005CALIB\020\000\022\n\n\006REGIST\020\001\022\020\n\014MOUTH_THRESH\020\002" +
      "\022\023\n\017YAWN_ALARM_TIME\020\003\022\023\n\017LEFT_EYE_THRESH" +
      "\020\004\022\024\n\020RIGHT_EYE_THRESH\020\005\022\023\n\017DOZE_ALARM_T" +
      "IME\020\006\022\024\n\020PHONE_ALARM_TIME\020\007\022\026\n\022SMOKING_A" +
      "LARM_TIME\020\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Settings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Settings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Settings_descriptor,
        new java.lang.String[] { "Actions", "Name", "MouthThresh", "YawnAlarmTime", "LeftEyeThresh", "RightEyeThresh", "DozeAlarmTime", "PhoneAlarmTime", "SmokingAlarmTime", "LeftDistractionLimit", "RightDistractionLimit", "DownDistractionLimit", "UpDistractionLimit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
